apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-nshy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-nshy
    app.kubernetes.io/part-of: test-app-nqkv
  name: devfile-sample-python-basic-nshy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-nshy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-nshy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-icyc-tenant/test-app-nqkv/devfile-sample-python-basic-nshy@sha256:7214f24ca7e2f0f8eda6fd4f39a4ec3c2f88d9c71e02d308a011160e38b35372
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
